---
server:
  port: 8882

# configuration for spring actuator
management:
  health:
    probes:
      enabled: true
spring:
  application:
    name: app-development-prototype-kafka-consumer
  cloud:
    config:
      enabled: false # disable retrieval of configuration from the Config Server
    function:
      definition: messageEventConsumer #list of the consumer/producer function names
    stream:
      kafka:
        bindings:
#          producer-out-0:
#            producer:
#              configuration:
#                value.serializer: com.amrut.prabhu.dto.coverters.MessageSerializer
          messageEventConsumer-in-0:
            consumer:
              configuration:
                value.deserializer: app.development.prototype.kafka.consumer.event.coverter.MessageEventDeSerializer
        binder:
          brokers: localhost:9092
      bindings:
#        producer-out-0:
#          destination: first-topic
#          producer:
#            useNativeEncoding: true # Enables using the custom serializer
        messageEventConsumer-in-0:
          destination: msp-dev-message-event-topic
          group: msp-message-event-group # consumer group name
          consumer:
            use-native-decoding: true # Enables using the custom deserializer
