---
server:
  port: 8882

# configuration for spring actuator
management:
  health:
    probes:
      enabled: true
spring:
  application:
    name: app-development-prototype-kafka-consumer
  cloud:
    config:
      enabled: false # disable retrieval of configuration from the Config Server
    function:
      definition: messageEventConsumer #list of the consumer/producer function names
    stream:
      kafka:
        bindings:
          #consumer
          messageEventConsumer-in-0:
            consumer:
              configuration:
                value.deserializer: app.development.prototype.kafka.consumer.event.converter.MessageEventDeSerializer
          #Batch consumer
          messageEventBatchConsumer-in-0:
            consumer:
              configuration:
                value.deserializer: app.development.prototype.kafka.consumer.event.converter.MessageEventDeSerializer
                max.poll.records: 10
                min.fetch.bytes: 5000
                fetch.max.wait.ms: 1000
        binder:
          brokers: localhost:9092
      bindings:
        #consumer
        messageEventConsumer-in-0:
          destination: msp-dev-message-event-topic
          group: msp-message-event-group # consumer group name
          consumer:
            use-native-decoding: true # Enables using the custom deserializer
        #Batch consumer
        messageEventBatchConsumer-in-0:
          destination: msp-dev-message-event-topic
          group: msp-message-event-group # consumer group name
          consumer:
            use-native-decoding: true # Enables using the custom deserializer
            batch-mode: true