---
server:
  port: 8882

# configuration for spring actuator
management:
  health:
    probes:
      enabled: true
# uncomment to see additional actuator endpoints for spring cloud stream
#  endpoints:
#    web:
#      exposure:
#        include:
#          - bindings
#          - "*"
spring:
  application:
    name: app-development-prototype-kafka-consumer
  cloud:
    config:
      enabled: false # disable retrieval of configuration from the Config Server
    function:
      definition: messageEventConsumer;messageEventBatchConsumer;messageEventWithKeyConsumer #list of the consumer/producer function names
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: ${KAFKA-BROKER:localhost:9092}
          configuration:
            default:
              key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde # add this if we are using kafka events with key
        bindings:
          #simple consumer config
          messageEventConsumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.kcm.msp.dev.app.development.prototype.kafka.consumer.event.converter.MessageEventDeSerializer
          #Batch consumer config
          messageEventBatchConsumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.kcm.msp.dev.app.development.prototype.kafka.consumer.event.converter.MessageEventDeSerializer
                max.poll.records: 5
                #min.fetch.bytes: 5000
                #fetch.max.wait.ms: 1000
          #consumer with key config
          messageEventWithKeyConsumer-in-0:
            consumer:
              configuration:
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value.deserializer: com.kcm.msp.dev.app.development.prototype.kafka.consumer.event.converter.MessageEventDeSerializer

      bindings:
        #simple consumer config
        messageEventConsumer-in-0:
          destination: msp-dev-message-event-topic
          group: msp-message-event-group-1 # consumer group name
          consumer:
            use-native-decoding: true # Enables using the custom deserializer
            #autoStartup: false
        #Batch consumer config
        messageEventBatchConsumer-in-0:
          destination: msp-dev-message-event-topic
          group: msp-message-event-group-2 # consumer group name
          consumer:
            use-native-decoding: true # Enables using the custom deserializer
            batch-mode: true
        #consumer with key config
        messageEventWithKeyConsumer-in-0:
          destination: msp-dev-message-event-topic
          group: msp-message-event-group-3 # consumer group name
          consumer:
            use-native-decoding: true # Enables using the custom deserializer
