---
server:
  port: 8883
# configuration for spring actuator
management:
  health:
    probes:
      enabled: true
spring:
  application:
    name: app-development-prototype-kafka-producer
  cloud:
    config:
      enabled: false # disable retrieval of configuration from the Config Server
    function:
      definition: messageEventProducer #list of the consumer/producer function names
    stream:
      kafka:
        bindings:
          messageEventProducer-out-0:
            producer:
              configuration:
                value.serializer: app.development.prototype.kafka.producer.event.converter.MessageEventSerializer
        binder:
          brokers: ${KAFKA-BROKER:localhost:9092}
      bindings:
        messageEventProducer-out-0:
          destination: msp-dev-message-event-topic
          producer:
            useNativeEncoding: true # Enables using the custom serializer