---
server:
  port: 8883
# configuration for spring actuator
management:
  health:
    probes:
      enabled: true
# uncomment to see additional actuator endpoints for spring cloud stream
#  endpoints:
#    web:
#      exposure:
#        include:
#          - bindings
#          - "*"
spring:
  application:
    name: app-development-prototype-kafka-producer
  cloud:
    config:
      enabled: false # disable retrieval of configuration from the Config Server
    function:
      definition: messageEventProducer #list of the consumer/producer function names
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: ${KAFKA-BROKER:localhost:9092}
          configuration:
            default:
              key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde # add this if you are using kafka events with key
        bindings:
          # simple producer
          messageEventProducer-out-0:
            producer:
              configuration:
                value.serializer: app.development.prototype.kafka.producer.event.converter.MessageEventSerializer

      bindings:
        # simple producer
        messageEventProducer-out-0:
          destination: msp-dev-message-event-topic
          producer:
            useNativeEncoding: true # Enables using the custom serializer